### PR TITLE
Initial release documentation for Analytics for PCF

### PR DESCRIPTION
**Pull request by pavankrish123**

### CODE REVIEW

**Comment by okilker** [comment]
Hi @pavankrish123, Looks good! I was going to quickly fill in some `YOUR-PRODUCT-NAME (Beta)` with AppDynamics Analytics for PCF. Will we be keeping the (Beta) tag as this is a new third tile that is still being fleshed out?

**Comment by jncd** [comment]
Hi @pavankrish123 
I can't build this doc because it looks like there's a broken link.
Can you supply an image called "ControllerAdminForAnalytics.png" ? or should that image not appear in the doc?
TIA, Jane

**Comment by pavankrish123** [comment]
Hi @jncd , 

My apologies, I think we should remove the reference completely. Shall I submit another PR? Please suggest 

`AdminPage`

**Comment by jncd** [comment]
That'd be great if you PR it. @pavankrish123 
I'm not sure if the "as shown below" referred to the image or something else.
Make sure to git pull the latest before creating your PR.

**Pull request merged**
